### ISSUE TITLE
Program does not start when following the Readme

### ISSUE THREAD

**Issue by vletoux** [oktadeveloper/okta-aspnetcore-mvc-example#11]
Indeed in appsetting there are 2 additional parameters to complete and their origin is not documented on the same page (newbie error);
    "APIToken": "{APIToken}",
    "OrgUrl": "{OrgUrl}"

![image](https://user-images.githubusercontent.com/10632326/38582660-ca4a8150-3d10-11e8-8ffa-f52ccd6a6bd4.png)

**Comment by torbenpedersen** [comment]
OrgUrl and Token information configuration can be found in the nodejs docs for configuration
https://developer.okta.com/okta-sdk-nodejs/jsdocs/

**Comment by vletoux** [comment]
Indeed but the section “Project configuration” of “read me” is incomplete. These 2 parameters are not described

**Comment by torbenpedersen** [comment]
Agreed, just added as workaround

**Comment by nbarbettini** [comment]
@vletoux @torbenpedersen I just updated the readme and some of the code.

Can you let me know if it's clear now? If not, I'll reopen this issue.

**Comment by vletoux** [comment]
Indeed. For me the issue is fixed
