### ISSUE TITLE
Error when accessing the AccountController

### ISSUE THREAD

**Issue by Porkstone** [oktadeveloper/okta-aspnetcore-mvc-example#13]
Hi, 

Today I created an Okta developer preview account to try this sample out. 

When I start the app and navigate to Account/Login I get an error:
InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://dev-298097.oktapreview.com/oauth2/v1/authorize/.well-known/openid-configuration'.

**Comment by kdcllc** [comment]
I am also not able to get beyond the following exception:
```
OpenIdConnectProtocolException: Message contains error: 'access_denied', error_description: 'User is not assigned to the client application.', error_uri: 'error_uri is null'.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```
This is the log from the Okta portal:
![image](https://user-images.githubusercontent.com/13120940/41076512-0674d59e-69e0-11e8-8cba-0c6ab2211887.png)

I assigned the user to the app and still get this exception.

**Comment by Porkstone** [comment]
I have resolved my issue now it was bad config.

I can't however get this working on our live Okta account.

**Comment by Porkstone** [comment]
Our live issue was due to OIDC being disabled, Support have fixed that so we are up and running now.

**Comment by nbarbettini** [comment]
@Porkstone Glad to hear you got everything working!

@kdcllc If you are still having this issue, can you post on https://devforum.okta.com? That error is not specifically related to this example. Thanks!
