### ISSUE TITLE
UAT

### ISSUE THREAD

**Issue by nbarbettini** [oktadeveloper/okta-aspnetcore-mvc-example#2]
Test this out on a machine that isn't Nate's.

**Comment by nbarbettini** [comment]
Hey @bdemers, can you try this out? It's very similar to the quickstart that you UATed earlier.

**Comment by vksantoshsunny** [comment]
Hi

I am having problems.. I think the solution need to include all the required nuget packages

**Comment by nbarbettini** [comment]
@vksantoshsunny Are you getting a specific error?

**Comment by nbarbettini** [comment]
Tested the app myself this evening. All working 👍
