### ISSUE TITLE
Not  An Issue : Information 

### ISSUE THREAD

**Issue by gmorieux** [oktadeveloper/okta-aspnetcore-mvc-example#4]
Thanks !
Helpful for my Application Reference Demo Server ....because most  people & developer not very easy with OpeniD 

After some time to debug ....

1) Require Nuget PM 4.3 --> previous versions not load properly ms aspnetcore.all and netcore.app
2) Require asp net core sdk V2 --> last VS 2017 did not install it v1 installed --> return un error
3) /oauth2/default/.well-known/openid-configuration return 401 (however public data ...?)  use instead /.well-known/openid-configuration working correct without auth 

Regards,

**Comment by nbarbettini** [comment]
Thanks for the feedback @gmorieux!

I'll make sure the readme notes that this requires ASP.NET Core 2.0 (and .NET Core 2.0 SDK).
