### ISSUE TITLE
Startup to match Appsettings

### ISSUE THREAD

**Issue by andrewvanbeek-okta** [oktadeveloper/okta-aspnetcore-mvc-example#6]
In Startup, I would think Configuration["okta:Issuer"] has to be renamed Configuration["okta:Authority"] to match the appsettings.json or vice versa

**Comment by Olivercomputing** [comment]
andrewvanbeek-okta is exactly correct. Making his suggested change permits the sample to run. 

I find it disappointing that nobody at Okta has made this correction in 6 weeks or so.

**Comment by nbarbettini** [comment]
Sorry for the long delay, that's my fault. I've merged #8 which fixes the issue(r).
